In [255]:
import numpy as np

In [256]:
def inverseToSolve(matrix_A, matrix_y):
    
    # Set an adjugate matrix of A
    adjMatrix_A = np.zeros((len(matrix_A), len(matrix_A)))
    
    for row in range(len(matrix_A)):
        
        # Set a determinant matrix of A
        detMatrix_A = np.zeros((len(matrix_A)-1, len(matrix_A)-1))
        
        for column in range(len(np.flip(matrix_A))):
            # record the position of the determinant matrix of A
            det_row_pos = 0
            det_column_pos = 0
            
            # indicating that whether an element is appended or not
            append = False
            
            # go through the matrix_A
            for det_row in range(len(detMatrix_A)+1):
                for det_column in range(len(np.flip(detMatrix_A))+1):
                    
                    if det_row != row and det_column != column:
                        detMatrix_A[det_row_pos][det_column_pos] = matrix_A[det_row][det_column]
                        append = True
                        det_column_pos += 1
                        
                # append happended
                if append:
                    det_column_pos = 0
                    det_row_pos += 1
                    append = False                
                
                adjMatrix_A[row][column] = np.linalg.det(detMatrix_A)
                
                # for the elements needed * -1 
                if (row + column) % 2 == 1 and row != column:
                    adjMatrix_A[row][column] *= -1
            
    # transpose the adjugate matrix of A        
    adjMatrix_A = np.transpose(adjMatrix_A)    
    
    
    print("adjugate matrix:\n{0}".format(adjMatrix_A))
    
    # the inverse of A = adj(A) / det(A)
    inverseMatrix_A = adjMatrix_A / np.linalg.det(matrix_A)
    
    # 解x
    x = np.zeros(len(matrix_A))
    for row in range(len(adjMatrix_A)):
        column_sum = 0 # 紀錄cloumn之和
        for column in range(len(np.flip(adjMatrix_A))):
            column_sum += inverseMatrix_A[row][column] * matrix_y[column]
        x[row] = column_sum
    
    print("\nx:\n{0}".format(np.array2string(x, separator=', ')))

In [257]:
a = np.array([[1,2],[3,4]])
y = [2, 5]

inverseToSolve(a,y)

adjugate matrix:
[[ 4. -2.]
 [-3.  1.]]

x:
[1. , 0.5]


In [258]:
a = np.array([[1,2,3],[3,4,5],[3,5,5]])
y = [2, 2, 5]

inverseToSolve(a,y)

adjugate matrix:
[[-5.  5. -2.]
 [-0. -4.  4.]
 [ 3.  1. -2.]]

x:
[-2.5,  3. , -0.5]
